--SINTAXE DO SELF JOIN -- https://www.youtube.com/watch?v=rX2I7OjLqWE
----SELECT TABELA_A, TABELA_B
--WHERE CONDICAO

SELECT*
FROM Customers
--VERIFICAR TODOS OS CLIENTES Q MORAM NA MESMA REGIAO
SELECT A.CONTACTNAME, A.REGION, B.CONTACTNAME, B.REGION
FROM Customers A, Customers B
WHERE A.Region=B.Region

--VERIFICAR NOME E DATA DE CONTRATACAO  DE TODOS OS FUNCIONARIOS QUE FORAM CONTRATADOS NO MESMO ANO
SELECT *
FROM Employees

SELECT A.FIRSTNAME, A.HIREDATE, B.FIRSTNAME, B.HIREDATE
FROM Employees A, Employees B
WHERE DATEPART (YEAR,A.HIREDATE) = DATEPART (YEAR,B.HIREDATE)

--DESAFIO VERFIFICAR NA TABELA DETALHE DE PEDIDO [Order Details] QUAIS PRODUTOS TEM O MESMO % DE DESCONTO

SELECT *
FROM [Order Details]

SELECT A.ProductID, A.Discount, B.ProductID, B.Discount
FROM [Order Details] A, [Order Details] B
WHERE A.Discount = B.Discount